nome = str(input("Ola, Bom dia! Digite seu nome:"))
print("Bom dia " + nome + "!")
tx_meta_basal = int(input("Agora por favor, me diga quantas calorias voce gasta em um dia sem fazer esforco:"))
cal_atv_fisica = int(input("Massa! Agora diga quantas calorias em media voce gasta quando faz um exercicio:"))
atv_semana = int(input("Uhh, e quantas vezes voce se exercita na semana?"))
mes_descanso = int(input("E quantos meses voce descansa?"))
cal_basal = (tx_meta_basal * 7 * 4 * 12)
cal_total_atv_fisica = (cal_atv_fisica * atv_semana * 4 * (12-mes_descanso))
calorias_gastas_ano = (cal_basal + cal_total_atv_fisica)
print(nome + "! voce gasta um total de:" + str(calorias_gastas_ano) + "calorias no ano!")